export type AndroidDeviceProfile = {
  manufacturer: string
  model: string
  formFactor: 'mobile' | 'tablet'
  androidVersions: ReadonlyArray<string>
}

export const androidDevices: ReadonlyArray<AndroidDeviceProfile> = [

  {
    manufacturer: 'Google',
    model: 'Pixel 9a',
    formFactor: 'mobile',
    androidVersions: ['15'],
  },
  {
    manufacturer: 'HONOR',
    model: 'HONOR Magic7 Pro',
    formFactor: 'mobile',
    androidVersions: ['15'],
  },
  {
    manufacturer: 'HONOR',
    model: 'HONOR Pad V9',
    formFactor: 'tablet',
    androidVersions: ['15'],
  },
  {
    manufacturer: 'Nothing',
    model: 'Phone (2a)',
    formFactor: 'mobile',
    androidVersions: ['14', '15'],
  },
  {
    manufacturer: 'Nothing',
    model: 'Phone (2a) Plus',
    formFactor: 'mobile',
    androidVersions: ['14', '15'],
  },
  {
    manufacturer: 'Nothing',
    model: 'Phone (3a)',
    formFactor: 'mobile',
    androidVersions: ['15'],
  },
  {
    manufacturer: 'OnePlus',
    model: 'OnePlus 12',
    formFactor: 'mobile',
    androidVersions: ['14', '15'],
  },
  {
    manufacturer: 'OnePlus',
    model: 'OnePlus 13',
    formFactor: 'mobile',
    androidVersions: ['15'],
  },
  {
    manufacturer: 'OnePlus',
    model: 'OnePlus Pad 2',
    formFactor: 'tablet',
    androidVersions: ['14', '15'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy A55 5G',
    formFactor: 'mobile',
    androidVersions: ['14', '15'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy S24',
    formFactor: 'mobile',
    androidVersions: ['14', '15'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy S24 Ultra',
    formFactor: 'mobile',
    androidVersions: ['14', '15'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy S25',
    formFactor: 'mobile',
    androidVersions: ['15'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy Z Fold 6',
    formFactor: 'mobile',
    androidVersions: ['14', '15'],
  },
  {
    manufacturer: 'Xiaomi',
    model: 'Xiaomi 14',
    formFactor: 'mobile',
    androidVersions: ['14', '15'],
  },
  {
    manufacturer: 'Xiaomi',
    model: 'Xiaomi 15',
    formFactor: 'mobile',
    androidVersions: ['15'],
  },
  {
    manufacturer: 'Xiaomi',
    model: 'Xiaomi Pad 7 Pro',
    formFactor: 'tablet',
    androidVersions: ['15'],
  },
  {
    manufacturer: 'FUJITSU',
    model: 'F-01L',
    formFactor: 'mobile',
    androidVersions: ['8.1'],
  },
  {
    manufacturer: 'Google',
    model: 'Pixel 10',
    formFactor: 'mobile',
    androidVersions: ['16'],
  },
  {
    manufacturer: 'Google',
    model: 'Pixel 10 Pro',
    formFactor: 'mobile',
    androidVersions: ['16'],
  },
  {
    manufacturer: 'Google',
    model: 'Pixel 10 Pro Fold',
    formFactor: 'mobile',
    androidVersions: ['16'],
  },
  {
    manufacturer: 'Google',
    model: 'Pixel 10 Pro XL',
    formFactor: 'mobile',
    androidVersions: ['16'],
  },
  {
    manufacturer: 'Google',
    model: 'Pixel 10a',
    formFactor: 'mobile',
    androidVersions: ['16'],
  },
  {
    manufacturer: 'Google',
    model: 'Pixel 3',
    formFactor: 'mobile',
    androidVersions: ['9'],
  },
  {
    manufacturer: 'Google',
    model: 'Pixel 5',
    formFactor: 'mobile',
    androidVersions: ['11'],
  },
  {
    manufacturer: 'Google',
    model: 'Pixel 6',
    formFactor: 'mobile',
    androidVersions: ['12', '12.1', '13'],
  },
  {
    manufacturer: 'Google',
    model: 'Pixel 6a',
    formFactor: 'mobile',
    androidVersions: ['12.1'],
  },
  {
    manufacturer: 'Google',
    model: 'Pixel 7',
    formFactor: 'mobile',
    androidVersions: ['13'],
  },
  {
    manufacturer: 'Google',
    model: 'Pixel 7 Pro',
    formFactor: 'mobile',
    androidVersions: ['13'],
  },
  {
    manufacturer: 'Google',
    model: 'Pixel 7a',
    formFactor: 'mobile',
    androidVersions: ['13'],
  },
  {
    manufacturer: 'Google',
    model: 'Pixel 8',
    formFactor: 'mobile',
    androidVersions: ['14', '15'],
  },
  {
    manufacturer: 'Google',
    model: 'Pixel 8 Pro',
    formFactor: 'mobile',
    androidVersions: ['14', '15'],
  },
  {
    manufacturer: 'Google',
    model: 'Pixel 8a',
    formFactor: 'mobile',
    androidVersions: ['14', '15'],
  },
  {
    manufacturer: 'Google',
    model: 'Pixel 9',
    formFactor: 'mobile',
    androidVersions: ['14', '15', '16'],
  },
  {
    manufacturer: 'Google',
    model: 'Pixel 9 Pro',
    formFactor: 'mobile',
    androidVersions: ['14', '15'],
  },
  {
    manufacturer: 'Google',
    model: 'Pixel 9 Pro Fold',
    formFactor: 'mobile',
    androidVersions: ['14', '15'],
  },
  {
    manufacturer: 'Google',
    model: 'Pixel 9 Pro XL',
    formFactor: 'mobile',
    androidVersions: ['14', '15'],
  },
  {
    manufacturer: 'Google',
    model: 'Pixel 9a',
    formFactor: 'mobile',
    androidVersions: ['15'],
  },
  {
    manufacturer: 'Google',
    model: 'Pixel Fold',
    formFactor: 'mobile',
    androidVersions: ['13', '14'],
  },
  {
    manufacturer: 'Google',
    model: 'Pixel Tablet',
    formFactor: 'tablet',
    androidVersions: ['13'],
  },
  {
    manufacturer: 'Lenovo',
    model: 'Lenovo Tab M11',
    formFactor: 'tablet',
    androidVersions: ['15'],
  },
  {
    manufacturer: 'Lenovo',
    model: 'Lenovo Tab P12',
    formFactor: 'tablet',
    androidVersions: ['15'],
  },
  {
    manufacturer: 'Motorola',
    model: 'moto g - 2025',
    formFactor: 'mobile',
    androidVersions: ['15'],
  },
  {
    manufacturer: 'Motorola',
    model: 'Moto G 5G',
    formFactor: 'mobile',
    androidVersions: ['15'],
  },
  {
    manufacturer: 'Motorola',
    model: 'moto g 5G (2022)',
    formFactor: 'mobile',
    androidVersions: ['13'],
  },
  {
    manufacturer: 'Motorola',
    model: 'moto g play - 2023',
    formFactor: 'mobile',
    androidVersions: ['13'],
  },
  {
    manufacturer: 'Motorola',
    model: 'moto g play - 2024',
    formFactor: 'mobile',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Motorola',
    model: 'moto g(30)',
    formFactor: 'mobile',
    androidVersions: ['12'],
  },
  {
    manufacturer: 'Motorola',
    model: 'moto g04',
    formFactor: 'mobile',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Motorola',
    model: 'moto g05',
    formFactor: 'mobile',
    androidVersions: ['15'],
  },
  {
    manufacturer: 'Motorola',
    model: 'moto g34 5G',
    formFactor: 'mobile',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Motorola',
    model: 'moto g54 5G',
    formFactor: 'mobile',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Motorola',
    model: 'motorola edge 30',
    formFactor: 'mobile',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Motorola',
    model: 'motorola edge 40',
    formFactor: 'mobile',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Motorola',
    model: 'motorola edge 40 neo',
    formFactor: 'mobile',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Motorola',
    model: 'motorola edge 50 fusion',
    formFactor: 'mobile',
    androidVersions: ['15'],
  },
  {
    manufacturer: 'Motorola',
    model: 'Motorola G20',
    formFactor: 'mobile',
    androidVersions: ['11'],
  },
  {
    manufacturer: 'Motorola',
    model: 'motorola razr plus 2024',
    formFactor: 'mobile',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'OnePlus',
    model: 'CPH2409',
    formFactor: 'mobile',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'OnePlus',
    model: 'CPH2415',
    formFactor: 'mobile',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'OnePlus',
    model: 'OnePlus 11 5G',
    formFactor: 'mobile',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'OnePlus',
    model: 'OnePlus Nord CE3 Lite',
    formFactor: 'mobile',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'OPPO',
    model: 'CPH2557',
    formFactor: 'mobile',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy A03s',
    formFactor: 'mobile',
    androidVersions: ['13'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy A06',
    formFactor: 'mobile',
    androidVersions: ['15'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy A10',
    formFactor: 'mobile',
    androidVersions: ['10'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy A12',
    formFactor: 'mobile',
    androidVersions: ['12'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy A13',
    formFactor: 'mobile',
    androidVersions: ['13', '14'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy A14',
    formFactor: 'mobile',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy A14 5G',
    formFactor: 'mobile',
    androidVersions: ['15'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy A52s',
    formFactor: 'mobile',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy A53 5G',
    formFactor: 'mobile',
    androidVersions: ['16'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy A54 5G',
    formFactor: 'mobile',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy Note 20 5G',
    formFactor: 'mobile',
    androidVersions: ['13'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy S20 FE 5G',
    formFactor: 'mobile',
    androidVersions: ['13'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy S21',
    formFactor: 'mobile',
    androidVersions: ['14', '15'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy S21 FE 5G',
    formFactor: 'mobile',
    androidVersions: ['16'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy S21 Plus',
    formFactor: 'mobile',
    androidVersions: ['14', '15'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy S21 Ultra',
    formFactor: 'mobile',
    androidVersions: ['14', '15'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy S22',
    formFactor: 'mobile',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy S22 Ultra',
    formFactor: 'mobile',
    androidVersions: ['13', '16'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy S23',
    formFactor: 'mobile',
    androidVersions: ['16'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy S23 Ultra',
    formFactor: 'mobile',
    androidVersions: ['13', '14'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy S24',
    formFactor: 'mobile',
    androidVersions: ['14', '16'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy S24 +',
    formFactor: 'mobile',
    androidVersions: ['16'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy S24 Ultra',
    formFactor: 'mobile',
    androidVersions: ['14', '16'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy S24+',
    formFactor: 'mobile',
    androidVersions: ['16'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy S25 Edge',
    formFactor: 'mobile',
    androidVersions: ['15'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy S25 Ultra',
    formFactor: 'mobile',
    androidVersions: ['15', '16'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy S25+',
    formFactor: 'mobile',
    androidVersions: ['16'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy S9',
    formFactor: 'mobile',
    androidVersions: ['10'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy Tab A7 Lite',
    formFactor: 'tablet',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy Tab A8',
    formFactor: 'tablet',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy Tab A9+ 5G',
    formFactor: 'tablet',
    androidVersions: ['13'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy Tab S3',
    formFactor: 'tablet',
    androidVersions: ['9'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy Tab S8',
    formFactor: 'tablet',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy Tab S8 Ultra',
    formFactor: 'tablet',
    androidVersions: ['13'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy Tab S9 5G',
    formFactor: 'tablet',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy Tab S9 Ultra 5G',
    formFactor: 'tablet',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy Tab S9+ 5G',
    formFactor: 'tablet',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy XCover Pro',
    formFactor: 'mobile',
    androidVersions: ['13'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy Z Flip 6',
    formFactor: 'mobile',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy Z Flip4',
    formFactor: 'mobile',
    androidVersions: ['13'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy Z Flip5',
    formFactor: 'mobile',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy Z Flip6',
    formFactor: 'mobile',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy Z Fold4',
    formFactor: 'mobile',
    androidVersions: ['13'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy Z Fold5',
    formFactor: 'mobile',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Galaxy Z Fold6',
    formFactor: 'mobile',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Samsung',
    model: 'S20 Plus 5G',
    formFactor: 'mobile',
    androidVersions: ['13'],
  },
  {
    manufacturer: 'Samsung',
    model: 'S23 Plus',
    formFactor: 'mobile',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Samsung',
    model: 'S24 Ultra',
    formFactor: 'mobile',
    androidVersions: ['16'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Samsung A05s',
    formFactor: 'mobile',
    androidVersions: ['15'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Samsung A15',
    formFactor: 'mobile',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Samsung A15 5G',
    formFactor: 'mobile',
    androidVersions: ['14', '16'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Samsung A35',
    formFactor: 'mobile',
    androidVersions: ['14', '15', '16'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Samsung Galaxy S21 FE 5G',
    formFactor: 'mobile',
    androidVersions: ['16'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Samsung Galaxy Tab S9 FE 5G',
    formFactor: 'tablet',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Samsung S23',
    formFactor: 'mobile',
    androidVersions: ['15', '16'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Samsung S25',
    formFactor: 'mobile',
    androidVersions: ['16'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Samsung S25 Ultra',
    formFactor: 'mobile',
    androidVersions: ['16'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Samsung S25+',
    formFactor: 'mobile',
    androidVersions: ['16'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Samsung SM-A266B',
    formFactor: 'mobile',
    androidVersions: ['16'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Samsung SM-A346N',
    formFactor: 'mobile',
    androidVersions: ['16'],
  },
  {
    manufacturer: 'Samsung',
    model: 'Samsung SM-A366E',
    formFactor: 'mobile',
    androidVersions: ['15', '16'],
  },
  {
    manufacturer: 'Samsung',
    model: 'SM-A145R',
    formFactor: 'mobile',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Samsung',
    model: 'SM-A256U1',
    formFactor: 'mobile',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Samsung',
    model: 'SM-A566b',
    formFactor: 'mobile',
    androidVersions: ['16'],
  },
  {
    manufacturer: 'Samsung',
    model: 'SM-A566E',
    formFactor: 'mobile',
    androidVersions: ['15'],
  },
  {
    manufacturer: 'Samsung',
    model: 'SM-G556B',
    formFactor: 'mobile',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Samsung',
    model: 'SM-S711N',
    formFactor: 'mobile',
    androidVersions: ['16'],
  },
  {
    manufacturer: 'Samsung',
    model: 'SM-S711U',
    formFactor: 'mobile',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Samsung',
    model: 'SM-S721U1',
    formFactor: 'mobile',
    androidVersions: ['15'],
  },
  {
    manufacturer: 'Samsung',
    model: 'SM-S906U1',
    formFactor: 'mobile',
    androidVersions: ['14', '16'],
  },
  {
    manufacturer: 'Samsung',
    model: 'SM-T738U',
    formFactor: 'tablet',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Samsung',
    model: 'SM-T870',
    formFactor: 'tablet',
    androidVersions: ['13'],
  },
  {
    manufacturer: 'Samsung',
    model: 'SM-X210',
    formFactor: 'tablet',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Samsung',
    model: 'SM-X710',
    formFactor: 'tablet',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'SHARP',
    model: 'AQUOS sense2 SH-01L',
    formFactor: 'mobile',
    androidVersions: ['9'],
  },
  {
    manufacturer: 'Sony',
    model: 'Xperia 10',
    formFactor: 'mobile',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Sony',
    model: 'Xperia 10 II',
    formFactor: 'mobile',
    androidVersions: ['12'],
  },
  {
    manufacturer: 'Sony',
    model: 'XQ-DC54',
    formFactor: 'mobile',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Sony',
    model: 'XQ-DQ72',
    formFactor: 'mobile',
    androidVersions: ['14'],
  },
  {
    manufacturer: 'Xiaomi',
    model: 'Redmi 6A',
    formFactor: 'mobile',
    androidVersions: ['8.1'],
  },
]
