# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: CI

on:
  workflow_dispatch: {}
  push:
    branches: [main, master]
    tags-ignore: ['**']
    paths-ignore: ['**.md', 'static/**']
  pull_request:
    paths-ignore: ['**.md', 'static/**']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Lint, test and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm ci --no-audit --no-fund
      - run: npm run lint
      - run: npm run test
      - run: npm run build
